module.exports = {
  reference: {
    'Overview': [
      'intro/intro',
      'intro/why-rust',
      'intro/why-webassembly',
      'intro/how-it-works',
      'faq/ink-vs-solidity',
    ],
    'Getting started': [
      'getting-started/setup',
      'getting-started/creating',
      'getting-started/compiling',
      'getting-started/running',
      'getting-started/deploying',
      'getting-started/calling',
      'getting-started/troubleshooting',
    ],
    'Basics': [
      'basics/contract-template',
      'basics/storing-values',
      'basics/reading-values',
      'basics/mutating-values',
      'basics/events',
      'basics/trait-definitions',
      'basics/cross-contract-calling',
      'basics/off-chain-testing',
      'basics/env-functions',
    ],
    'Macros & Attributes': [
      'ink-macros/overview',
      'ink-macros/constructor',
      'ink-macros/message',
      'ink-macros/event',
      'ink-macros/anonymous',
      'ink-macros/implementation',
      'ink-macros/namespace',
      'ink-macros/payable',
      'ink-macros/selector',
      'ink-macros/storage',
      'ink-macros/topic',
    ],
    'Storage & Data Structures': [
      'datastructures/overview',
      'datastructures/hashmap',
      'datastructures/hashmap-impls',
      'datastructures/spread-packed',
      'datastructures/opting-out',
      'datastructures/dynamic-allocation',
      'datastructures/custom',
    ],
    'Examples': [
      'examples/overview',
    ],
    'cargo-contract CLI': [
      'cargo-contract/overview',
    ],
    'Canvas Test Network': [
      'canvas/overview',
    ],
    'FAQ': [
      'faq/intro',
    ],
  },
};
