module.exports = {
  reference: {
    'Overview': [
      'intro/intro',
      'intro/why-rust',
      'intro/why-webassembly',
      'intro/how-it-works',
      'intro/ink-vs-solidity',
      'intro/ink-vs-cosmwasm',
    ],
    'Monthly Update': [
      'monthly-update/overview',
      'monthly-update/2022/10',
      'monthly-update/2022/09',
      'monthly-update/2022/08',
      'monthly-update/2022/07',
      'monthly-update/2022/06',
      'monthly-update/2022/05',
      'monthly-update/2022/04',
      'monthly-update/2022/03',
    ],
    'Getting started': [
      'getting-started/setup',
      'getting-started/creating',
      'getting-started/compiling',
      'getting-started/running',
      'getting-started/deploying',
      'getting-started/calling',
      'getting-started/troubleshooting',
    ],
    'Basics': [
      'basics/contract-template',
      'basics/storing-values',
      'basics/reading-values',
      'basics/mutating-values',
      'basics/events',
      'basics/trait-definitions',
      'basics/cross-contract-calling',
      'basics/upgradeability',
      'basics/testing',
      'basics/env-functions',
      'basics/metadata',
    ],
    'Macros & Attributes': [
      'macros-attributes/overview',
      'macros-attributes/contract',
      'macros-attributes/anonymous',
      'macros-attributes/constructor',
      'macros-attributes/event',
      'macros-attributes/implementation',
      'macros-attributes/message',
      'macros-attributes/namespace',
      'macros-attributes/payable',
      'macros-attributes/selector',
      'macros-attributes/storage',
      'macros-attributes/topic',
      'macros-attributes/chain-extension',
    ],
    'Storage & Data Structures': [
      'datastructures/overview',
      'datastructures/mapping',
      'datastructures/spread-storage-layout',
      'datastructures/custom',
    ],
    'Examples': [
      'examples/overview',
    ],
    'cargo-contract CLI': [
      'cargo-contract/overview',
    ],
    'Live Testnet': [
      'testnet/overview',
    ],
    'FAQ': [
      'faq/faq',
    ],
    'Brand Assets': [
      'brand-assets/ink',
      'brand-assets/community-badges',
      'brand-assets/cargo-contract',
    ],
  },
};
